name: Latest blog posts
on:
  schedule: # Run workflow automatically
    - cron: '30 * * * *' # Runs every hour, on the 30 minutes.
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://http://rodneydyer.com/rss/"
